### PR TITLE
commit on CaseList TicketList

### PR DESCRIPTION
**Pull request by puwhokori**

### CODE REVIEW

**Comment by mbenhallouk** [comment]
Hey,

You did write the description, can you please write what's your intention with this pull request.

Thanks,
Amine

**Comment by puwhokori** [comment]
I was trying to create chek list - new features



Sent from Samsung Mobile on O2


-------- Original message --------

**Comment by mbenhallouk** [comment]
Ok I see, can I ask you to add the title to the document before I merge it.

Thanks a lot,
Amine

**Comment by puwhokori** [comment]
Ok added. Thanks
Peter



Sent from Samsung Mobile on O2


-------- Original message --------

**Pull request merged**
